### ISSUE TITLE
Application port not open in security group

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/github-actions-deploy-docker-to-ec2#32]
If the exposed port is different than the application port running in the EC2 instance, incoming traffic will be blocked.
We should add the ELB exposed port in the security group for it to work. 
We can create a new security group only for the load balancer or use the existing one.

We can 
Create a Security Group for the Load Balancer ("LB-SG")
Create a Security Group for the EC2 instances ("App-SG")
In App-SG, permit inbound traffic on the desired port from LB-SG

We should keep in mind that we'll need access through SSH to the EC2 instance to run Ansible

**Comment by mickmcgrath13** [comment]
> We should keep in mind that we'll need access through SSH to the EC2 instance to run Ansible

This can (should?) be done in AWS EC2 Instance Connect from the AWS Console.  That way we don't have to worry about creating/sharing/managing `.pem`s

> If the exposed port is different than the application port running in the EC2 instance, incoming traffic will be blocked.

I don't think I understand why this would happen. I'd expect that whatever the LB has (`:80` or `:443` or `whatever-the-app-set`) shouldn't matter because it should be re-mapping it to `whatever-the-app-set` for the instance port. Is that not the case?

If that's not happening, can you share an example of what you're seeing?

**Comment by mickmcgrath13** [comment]
looking at the [SG terraform](https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/operations/deployment/terraform/security-group.tf#L16-L34), i could see how if the LB terraform sets 80 or 443, the security group isn't, so traffic wouldn't go through.
