### ISSUE TITLE
LoadBalancer S3 Bucket Logs not deleted on destroy

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/github-actions-deploy-docker-to-ec2#38]
```
Error: error deleting S3 Bucket (bitovi-devops-xxx-logs): BucketNotEmpty: The bucket you tried to delete is not empty
```

In order to purge it and delete it on deletion, we could add the following to the terraform code

```
force_destroy = true
```

**Comment by PhillypHenning** [comment]
I agree with both;
If we can’t delete it in terraform then our only option is to use the CLI
Example bitops config
```
delete_s3: string
choice:
- hard
- soft
- no / false
```
Hard being a purge and removal. Soft being a tagging and no being leave it.

If you want to do this as a strict boolean then the options would be;
forced delete
tag for deletion and notify (default)

**Comment by mickmcgrath13** [comment]
the ELB bucket is named from the GITHUB_IDENTIFIER, right?  One caveat to a full delete is if you need to recreate after delete, you have to wait some time for s3 buckets.  Phil's recommendation covers that.

I'd personally go with 2 flags: (`delete_s3`: boolean, `delete_s3_soft`: boolean - defaults to true, only relevant if `delete_s3` is boolean) instead of the `enum` approach, but either works so we have options :)
